export class SuggestedHouse{
  public Aidat: string;
  public Depozito: string;
  public Ilanbasligi: string;
  public Ilanlinki: string;
  public Kimden: string;
  public SiteIcerisinde: string;
  public age: string;
  public balcony: string;
  public banyosayisi: string;
  public contact_name: string;
  public coordinates: string;
  public esyali: string;
  public floor: string;
  public heating: string;
  public kat: string;
  public kullanimdurumu: string;
  public lat: string;
  public listingID: number;
  public lon: string;
  public numberoffloors: string;
  public numberofrooms: string;
  public price: number;
  public squaremeter: number;
  public web_scraper_order: string;
  public web_scraper_start_url: string;
  public __v: number;
  public _id: string;
}
